### Default
GET http://localhost:2907

### Retrieve all movies
GET http://localhost:2907/movies

### Retrieve a movie by ID
GET http://localhost:2907/movies/2d0b4fc7-bec0-468c-b979-fad67822a98b

### Retrieve a movie by ID
GET http://localhost:2907/movies?genre=crime

### Create a movie
POST http://localhost:2907/movies
Content-Type: application/json

{
  "title": "El Conde de Montecristo",
  "year": 2002,
  "director": "Kevin Reynolds",
  "duration": 131,
  "poster": "https://m.media-amazon.com/images/M/MV5BMDM0ZWRjZDgtZWI0MS00ZTIzLTg4MWYtZjU5MDEyMDU0ODBjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
  "rate": 9,
  "genre": [
      "Action",
      "Crime",
      "Drama"
    ]
}